# Generated by Django 2.2 on 2020-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200407_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
