# Generated by Django 2.2 on 2020-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20200408_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferbatch',
            name='batch_info',
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='batch_ref',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
