# Generated by Django 2.2 on 2020-04-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200324_1425'),
        ('stock', '0010_auto_20200411_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferbatch',
            name='batch_ref',
        ),
        migrations.AddField(
            model_name='transferbatch',
            name='batch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.BatchInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transferbatch',
            name='stock_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_batches', to='stock.StockTransfer'),
        ),
    ]
