# Generated by Django 2.2 on 2020-04-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20200417_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferbatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ProductBatch'),
        ),
    ]
