# Generated by Django 2.2 on 2020-05-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0008_auto_20190806_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspreference',
            name='payment_method',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='outletpreference',
            name='payment_method',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
