
# Generated by Django 2.2 on 2020-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190708_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='receipt',
        ),
        migrations.AddField(
            model_name='register',
            name='register_id',
            field=models.CharField(default=' ', max_length=244),
            preserve_default=False,
        ),
    ]
