# Generated by Django 2.2 on 2020-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200326_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_id',
            field=models.CharField(max_length=244, null=True),
        ),
    ]
