# Generated by Django 2.2 on 2020-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200326_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='original_name',
            field=models.CharField(default=' ', max_length=244),
            preserve_default=False,
        ),
    ]
