# Generated by Django 2.2 on 2020-03-30 18:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_register_original_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='register',
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
