# Generated by Django 2.2 on 2020-02-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200204_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0),
        ),
    ]
