# Generated by Django 2.2 on 2020-03-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_auto_20191210_0014'),
        ('products', '0036_product_global_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='outlet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Outlet'),
        ),
    ]
