# Generated by Django 2.2 on 2020-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_quantity_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='autofill_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='avarage_unit_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_tax_retail_price',
            field=models.IntegerField(default=0),
        ),
    ]
