# Generated by Django 2.2 on 2020-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200115_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_mobile_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
