# Generated by Django 2.2 on 2020-02-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200220_1326'),
        ('profiles', '0005_auto_20200213_1030'),
    ]

    operations = [
    ]
