# Generated by Django 2.2 on 2020-02-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20191202_0954'),
        ('products', '0035_auto_20200206_1429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0029_merge_20200212_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='orders.SupplierOrderDetails'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                default='Incomplete order form', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='business',
            field=models.ManyToManyField(to='business.Business'),
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='business',
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='supplierscontacts',
            name='country',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.Country'),
        ),
        migrations.CreateModel(
            name='OrdersProducts',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_unit_price', models.IntegerField(blank=True, null=True)),
                ('sku_number', models.IntegerField(null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('backup_supplier', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='orders.Suppliers')),
                ('current_supplier', models.ForeignKey(blank=True, null=True,
                                                       on_delete=django.db.models.deletion.CASCADE, related_name='current', to='orders.Suppliers')),
                ('deleted_by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True,
                                                         on_delete=django.db.models.deletion.CASCADE, related_name='primary', to='orders.Suppliers')),
                ('product', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product')),
            ],
            options={
                'unique_together': {('product_name', 'sku_number', 'product_quantity', 'order')},
            },
        ),
    ]
