# Generated by Django 2.2 on 2020-03-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_business'),
        ('orders', '0034_auto_20200308_2008'),
        ('orders', '0032_auto_20200306_1516'),
    ]

    operations = [
    ]
