# Generated by Django 2.2 on 2020-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_merge_20200311_1634'),
        ('orders', '0035_merge_20200311_1158'),
        ('orders', '0035_merge_20200311_0107'),
    ]

    operations = [
    ]
