# Generated by Django 2.2 on 2020-03-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_merge_20200311_1136'),
        ('orders', '0035_merge_20200311_0107'),
    ]

    operations = [
    ]
