# Generated by Django 2.2 on 2020-03-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_merge_20200312_1515'),
        ('orders', '0036_merge_20200312_1611'),
    ]

    operations = [
    ]
