# Generated by Django 2.2 on 2020-03-31 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0038_auto_20200324_1425'),
        ('orders', '0037_merge_20200312_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('batch_ref', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING_ORDER', 'A order which is pending'), ('PENDING_DELIVERY', 'A delivery yet to be made'), ('NOT_ACCEPTED', 'An order which has been cancelled'), ('NOT_RECEIVED', 'An order which is yet to be recieved'), ('NOT_ACCEPTED', 'An order which has yet to be accepted'), ('RETURNED', 'An order which is returned'), ('IN_STOCK', 'Still in stock'), ('OUT_OF_STOCK', 'Out of stock'), ('EXPIRED', 'Expired Products')], default='PENDING_ORDER', max_length=10)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
