# Generated by Django 2.2 on 2020-03-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_productbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('PENDING_ORDER', 'A order which is pending'), ('PENDING_DELIVERY', 'A delivery yet to be made'), ('NOT_ACCEPTED', 'An order which has been cancelled'), ('NOT_RECEIVED', 'An order which is yet to be recieved'), ('NOT_ACCEPTED', 'An order which has yet to be accepted'), ('RETURNED', 'An order which is returned'), ('IN_STOCK', 'Still in stock'), ('OUT_OF_STOCK', 'Out of stock'), ('EXPIRED', 'Expired Products')], default='PENDING_ORDER', max_length=25),
        ),
    ]
