# Generated by Django 2.2 on 2020-04-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_auto_20191210_0014'),
        ('orders', '0040_auto_20200409_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='outlets.Outlet'),
        ),
    ]
