# Generated by Django 2.2 on 2020-04-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_productbatch_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
