# Generated by Django 2.2 on 2020-04-28 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import healthid.utils.app_utils.id_generator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0042_auto_20200422_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(default=healthid.utils.app_utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'A supplier order which has been started'), ('PENDING_APPROVAL', 'A delivery yet to be made'), ('CANCELLED', 'An order which has been cancelled'), ('APPROVED', 'An order which is yet to be recieved'), ('PENDING_DELIVERY', 'An order which has yet to be accepted'), ('RECEIVED', 'An order which is returned'), ('CLOSED', 'Still in stock')], default='STARTED', max_length=10)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
