# Generated by Django 2.2 on 2020-04-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_supplierorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.CharField(choices=[('STARTED', 'A supplier order which has been started'), ('PENDING_APPROVAL', 'A delivery yet to be made'), ('CANCELLED', 'An order which has been cancelled'), ('APPROVED', 'An order which is yet to be recieved'), ('PENDING_DELIVERY', 'An order which has yet to be accepted'), ('RECEIVED', 'An order which is returned'), ('CLOSED', 'Still in stock')], default='STARTED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='supplierorder',
            unique_together={('order', 'supplier')},
        ),
    ]
