# Generated by Django 2.2 on 2020-05-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0013_merge_20200421_1903'),
        ('orders', '0044_auto_20200428_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_outlet', to='outlets.Outlet'),
        ),
    ]
