# Generated by Django 2.2 on 2020-05-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_userbusiness'),
        ('orders', '0046_auto_20200505_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='business.Business'),
        ),
    ]
