# Generated by Django 2.2 on 2020-05-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0013_merge_20200421_1903'),
        ('orders', '0048_supplieroutletcontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierscontacts',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='supplieroutletcontacts',
            name='dataKey',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplieroutletcontacts',
            name='dataValue',
            field=models.CharField(max_length=255, null=True),
        )
    ]
