# Generated by Django 2.2 on 2020-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_sales_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipttemplate',
            name='footer_message',
            field=models.CharField(default='Thank you for shopping with us. Please come again!', max_length=255),
        ),
        migrations.AddField(
            model_name='receipttemplate',
            name='logo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
