# Generated by Django 2.2 on 2020-04-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_auto_20200330_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='footer',
        ),
    ]
