# Generated by Django 2.2 on 2020-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_remove_receipt_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttemplate',
            name='logo',
            field=models.URLField(),
        ),
    ]
