# Generated by Django 2.2 on 2020-03-31 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_20200224_1430'),
        ('products', '0038_auto_20200324_1425'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0016_auto_20191219_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('quantity_sold', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('transaction_date', models.DateField()),
                ('cashier', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sale_cashier', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sale_customer', to='profiles.Profile')),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
