# Generated by Django 2.2 on 2020-04-07 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_auto_20191210_0014'),
        ('sales', '0019_auto_20200404_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperformance',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_performance', to='outlets.Outlet'),
            preserve_default=False,
        ),
    ]
