# Generated by Django 2.2 on 2020-04-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_salesperformance_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperformance',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_customer', to='profiles.Profile'),
        ),
    ]
