# Generated by Django 2.2 on 2020-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_auto_20200507_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Card', 'Card'), ('Bank_Transfer', 'Bank_Transfer')], max_length=18),
        ),
    ]
