# Generated by Django 2.2 on 2020-05-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'The Payment method involving cash'), ('CARD', 'The Payment method involving card'), ('BANK_TRANSFER', 'The Payment method involving transfer to bank'), ('STORE_CREDIT', 'The Payment method involving store credits')], default='CASH', max_length=30),
        ),
    ]
