# Generated by Django 2.2 on 2020-06-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20200528_1245'),
        ('sales', '0028_auto_20200528_1629'),
    ]

    operations = [
    ]
