# Generated by Django 2.2 on 2020-05-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20200528_1245'),
        ('sales', '0028_auto_20200528_1629'),
        ('sales', '0028_auto_20200528_0939'),
    ]

    operations = [
    ]
