# Generated by Django 2.2 on 2020-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_merge_20200601_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Card', 'Card'), ('Bank_Transfer', 'Bank_Transfer'), ('Split', 'Split')], max_length=18),
        ),
    ]
