# Generated by Django 2.2 on 2020-06-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20200601_1232'),
        ('sales', '0029_merge_20200601_1028'),
        ('sales', '0029_merge_20200530_1203'),
    ]

    operations = [
    ]
