# Generated by Django 2.2 on 2020-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_merge_20200602_1213'),
        ('sales', '0031_merge_20200602_0955'),
    ]

    operations = [
    ]
