# Generated by Django 2.2 on 2020-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_merge_20200603_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='batch_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
