# Generated by Django 2.2 on 2020-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_saledetail_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='return_sale_id',
            field=models.IntegerField(default=0),
        ),
    ]
