# Generated by Django 2.2 on 2020-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_auto_20191210_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletuser',
            name='is_current_outlet',
            field=models.BooleanField(default=False),
        ),
    ]
