# Generated by Django 2.2 on 2020-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0010_auto_20191210_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='tax_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
