# Generated by Django 2.2 on 2020-04-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0011_outletuser_is_current_outlet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outletuser',
            old_name='is_current_outlet',
            new_name='is_default_outlet',
        ),
    ]
