# Generated by Django 2.2 on 2020-04-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0012_auto_20200411_1113'),
        ('outlets', '0011_outlet_tax_number'),
    ]

    operations = [
    ]
